// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherForecastv2.Data;

#nullable disable

namespace WeatherForecastv2.Migrations
{
    [DbContext(typeof(WeatherForecastContext))]
    [Migration("20251113122000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherForecastv2.Models.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ApparentTemperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<int>("CloudCover")
                        .HasColumnType("int");

                    b.Property<DateTime>("FetchDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Humidity2m")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId1")
                        .HasColumnType("int");

                    b.Property<double>("Precipitation")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<int>("PrecipitationProbability")
                        .HasColumnType("int");

                    b.Property<string>("PrecipitationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PressureSurface")
                        .HasPrecision(8, 2)
                        .HasColumnType("float(8)");

                    b.Property<double>("Temperature2m")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<int>("UvIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Visibility")
                        .HasPrecision(8, 2)
                        .HasColumnType("float(8)");

                    b.Property<int>("WeatherModelId")
                        .HasColumnType("int");

                    b.Property<double>("WindSpeed10m")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("LocationId1");

                    b.HasIndex("WeatherModelId");

                    b.ToTable("Forecast");
                });

            modelBuilder.Entity("WeatherForecastv2.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("float(10)");

                    b.Property<double>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("float(10)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("WeatherForecastv2.Models.WeatherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeatherModel");
                });

            modelBuilder.Entity("WeatherForecastv2.Models.Forecast", b =>
                {
                    b.HasOne("WeatherForecastv2.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherForecastv2.Models.Location", null)
                        .WithMany("Forecasts")
                        .HasForeignKey("LocationId1");

                    b.HasOne("WeatherForecastv2.Models.WeatherModel", "WeatherModel")
                        .WithMany("Forecasts")
                        .HasForeignKey("WeatherModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("WeatherModel");
                });

            modelBuilder.Entity("WeatherForecastv2.Models.Location", b =>
                {
                    b.Navigation("Forecasts");
                });

            modelBuilder.Entity("WeatherForecastv2.Models.WeatherModel", b =>
                {
                    b.Navigation("Forecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
