// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherForecast.Infrastructure.Persistence;

#nullable disable

namespace WeatherForecast.Infrastructure.Migrations
{
    [DbContext(typeof(WeatherForecastContext))]
    partial class WeatherForecastContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("WeatherForecast.Domain.Entities.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ApparentTemperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("CloudCover")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Humidity2m")
                        .HasPrecision(5, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precipitation")
                        .HasPrecision(5, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("PrecipitationProbability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrecipitationType")
                        .HasColumnType("TEXT");

                    b.Property<double>("PressureSurface")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature2m")
                        .HasPrecision(5, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("UvIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Visibility")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<int>("WeatherModelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WindSpeed10m")
                        .HasPrecision(5, 2)
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ValidDate");

                    b.HasIndex("WeatherModelId");

                    b.HasIndex("LocationId", "FetchDate");

                    b.ToTable("Forecasts", (string)null);
                });

            modelBuilder.Entity("WeatherForecast.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 5)
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasPrecision(10, 5)
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("WeatherForecast.Domain.Entities.WeatherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WeatherModels", (string)null);
                });

            modelBuilder.Entity("WeatherForecast.Domain.Entities.Forecast", b =>
                {
                    b.HasOne("WeatherForecast.Domain.Entities.Location", "Location")
                        .WithMany("Forecasts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherForecast.Domain.Entities.WeatherModel", "WeatherModel")
                        .WithMany("Forecasts")
                        .HasForeignKey("WeatherModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("WeatherModel");
                });

            modelBuilder.Entity("WeatherForecast.Domain.Entities.Location", b =>
                {
                    b.Navigation("Forecasts");
                });

            modelBuilder.Entity("WeatherForecast.Domain.Entities.WeatherModel", b =>
                {
                    b.Navigation("Forecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
